#!/bin/bash
set -euo pipefail

# If an argument is given we replace everything after the plus sign with
# that argument. Used for nightly version naming.
replacePlus="${1:-}"

sign() {
	f="$1"
	base="$2"
	exe="$base/syncthing"
	metadir=".metadata"
	if [ -f "$base/syncthing.exe" ] ; then
		exe="$base/syncthing.exe"
		metadir="metadata"
	fi
	if [ -f "$exe" ] ; then
		echo Signing "$base ($f)"
		rm -rf "$base/$metadir"
		mkdir -p "$base/$metadir"
		( echo "$f"; cat "$exe" ) | stsigtool sign "$PRIVATE_KEY" > "$base/$metadir/release.sig"
	fi
}

for f in *.tar.gz; do
        case "$f" in
	syncthing-source-*.tar.gz)
		;;
	*)
		base="${f%.tar.gz}"
		tar zxf "$f"
		if [[ $replacePlus != "" ]] ; then
			newbase=${base/+*/$replacePlus}
			mv "$base" "$newbase"
			base="$newbase"
		fi
		sign "$f" "$base"
		rm -f "$f"
		tar zcf "$f" "$base"
		rm -rf "$base"
	;;
	esac
done

for f in *.zip; do
	base="${f%.zip}"
	unzip -q "$f"
	if [[ $replacePlus != "" ]] ; then
		newbase=${base/+*/$replacePlus}
		mv "$base" "$newbase"
		base="$newbase"
	fi
	sign "$f" "$base"
	rm -f "$f"
	zip -q -r "$f" "$base"
	rm -rf "$base"
done

